gem 'mecab-ruby'
gem 'rack'
gem 'padrino','0.10.7'
gem 'padrino-core','0.10.7'
gem 'sinatra'
gem 'sinatra-xsendfile'
gem 'sinatra-reloader'
gem 'mechanize'
gem 'mongoid',"2.3.0"
gem 'mongo',"1.7.0"
gem 'bson',"1.7.0"
gem 'bson_ext',"1.7.0"
gem 'exifr'
gem 'rmagick'
gem 'will_paginate'
